config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/VIScERaL:
      branch: main
      repo: https://github.com/stevenjgibbons/VIScERaL
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/VIScERaL git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-lilac-ibis.sh
        container: qc.acc_bumpy-mustard-uakari
  QC.Doc:
    repos:
      github.com/stevenjgibbons/VIScERaL find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-copper-axolotl.sh
        container: qc.doc_snoopy-amber-robin
      github.com/stevenjgibbons/VIScERaL git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-buff-kudu.sh
        container: qc.doc_bluesy-yellow-retriever
      github.com/stevenjgibbons/VIScERaL markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-cerulean-caracal.sh
        container: qc.doc_pretty-olive-mastiff
  QC.Lic:
    repos:
      github.com/stevenjgibbons/VIScERaL licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-sepia-echidna.sh
        container: qc.lic_woozy-cerise-warthog
  QC.Met:
    repos:
      github.com/stevenjgibbons/VIScERaL cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-mustard-squid.sh
        container: qc.met_slimy-cinnabar-reindeer
  QC.Sec:
    repos:
      github.com/stevenjgibbons/VIScERaL bandit:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-bronze-beagle.sh
        container: qc.sec_goopy-violet-indri
  QC.Sty:
    repos:
      github.com/stevenjgibbons/VIScERaL flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-peach-booby.sh
        container: qc.sty_homey-olive-quail
  QC.Ver:
    repos:
      github.com/stevenjgibbons/VIScERaL get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-lime-cougar.sh
        container: qc.ver_freaky-silver-albatross
timeout: 5400
