config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/VIScERaL:
      branch: main
      repo: https://github.com/stevenjgibbons/VIScERaL
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/VIScERaL git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-ochre-frigatebird.sh
        container: qc.acc_goopy-cyan-tarantula
  QC.Doc:
    repos:
      github.com/stevenjgibbons/VIScERaL find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-taupe-mongoose.sh
        container: qc.doc_chewy-rose-saola
      github.com/stevenjgibbons/VIScERaL git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-mustard-axolotl.sh
        container: qc.doc_homely-olive-sloth
      github.com/stevenjgibbons/VIScERaL markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-heliotrope-cuscus.sh
        container: qc.doc_droopy-auburn-fousek
  QC.Lic:
    repos:
      github.com/stevenjgibbons/VIScERaL licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-indigo-deer.sh
        container: qc.lic_stinky-seashell-discus
  QC.Met:
    repos:
      github.com/stevenjgibbons/VIScERaL cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-cardinal-snake.sh
        container: qc.met_sickly-rose-chihuahua
  QC.Sec:
    repos:
      github.com/stevenjgibbons/VIScERaL bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-harlequin-capybara.sh
        container: qc.sec_freaky-black-moorhen
  QC.Sty:
    repos:
      github.com/stevenjgibbons/VIScERaL flake8:
        commands:
        - /usr/bin/env sh .sqa/script.beady-smalt-deer.sh
        container: qc.sty_seedy-myrtle-mau
  QC.Ver:
    repos:
      github.com/stevenjgibbons/VIScERaL get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-sepia-caracal.sh
        container: qc.ver_beady-firebrick-budgerigar
timeout: 5400
