config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/VIScERaL:
      branch: main
      repo: https://github.com/stevenjgibbons/VIScERaL
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/VIScERaL git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-purple-seahorse.sh
        container: qc.acc_beady-mustard-mouse
  QC.Doc:
    repos:
      github.com/stevenjgibbons/VIScERaL find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-xanthic-tapir.sh
        container: qc.doc_thirsty-cornflower-dhole
      github.com/stevenjgibbons/VIScERaL git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-linen-hippopotamus.sh
        container: qc.doc_tasty-cardinal-snake
      github.com/stevenjgibbons/VIScERaL markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-myrtle-numbat.sh
        container: qc.doc_clammy-cerulean-coati
  QC.Lic:
    repos:
      github.com/stevenjgibbons/VIScERaL licensee:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-blue-fowl.sh
        container: qc.lic_skimpy-turquoise-harrier
  QC.Met:
    repos:
      github.com/stevenjgibbons/VIScERaL cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-cerulean-chihuahua.sh
        container: qc.met_skinny-cream-eel
  QC.Sec:
    repos:
      github.com/stevenjgibbons/VIScERaL bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-asparagus-cougar.sh
        container: qc.sec_muzzy-lemon-moth
  QC.Sty:
    repos:
      github.com/stevenjgibbons/VIScERaL flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-zucchini-seahorse.sh
        container: qc.sty_queasy-mauve-serval
  QC.Ver:
    repos:
      github.com/stevenjgibbons/VIScERaL get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-coral-audemer.sh
        container: qc.ver_lovely-azure-hamster
timeout: 5400
